name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar versión de Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ Crear y activar entorno virtual
      - name: Create and activate virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip

      # 4️⃣ Instalar dependencias dentro del venv
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install pandas==2.2.2 pyarrow==15.0.2 holidays==0.47 boto3==1.34.129 s3fs==2024.3.0 pytest==8.3.2 moto==5.0.9

      # 5️⃣ Ejecutar pruebas unitarias y generar reporte
      - name: Run unit tests
        run: |
          source .venv/bin/activate
          mkdir -p reports
          pytest -v --junitxml=reports/test-results.xml

      # 6️⃣ Configurar credenciales AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 7️⃣ Subir reporte de pruebas a S3
      - name: Upload test results to S3
        run: |
          source .venv/bin/activate
          aws s3 cp reports/test-results.xml s3://aws-glue-assets-122323568198-us-east-1/a/test-results.xml
